name: Deploy Commands Globally

on:
  push:
    branches:
      - main

jobs:
  deploy_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Deploy commands globally
        run: npm run deploy-commands-global
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
