name: Prettier Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  oxlint:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Prettier check
        run: yarn run check-format
